baseURL = "https://fgetdapain.github.io/"
languageCode = "zh-CN"
title = "FgetDaPain"
theme = "mainroad" # set the theme
paginate = "10" # Number of posts per page


[Author] # Used in authorbox
    name = "FgetDaPain"
    bio = "A Pythoner, Penetration Tester. 一个热爱学习的人."
    #avatar = "img/avatar.png"

[Params]
    subtitle = "技术与生活" # Subtitle of your site. Used in site header
    description = " FgetDaPain's Personal blog about everything" # Description of your site. Used in meta description
    opengraph = false # Enable OpenGraph if true
    twitter_cards = false # Enable Twitter Cards if true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true # Show authorbox at bottom of pages if true
    post_navigation = true # Show post navigation at bottom of pages if true
    postSections = ["posts"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    #dateformat = "2006-01-02" # change the format of dates

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

    # Enable "Social" widget, if any of "social_*" set a value
    #social_facebook = "username"
    #social_twitter = "username"
    #social_linkedin = "username"
    #social_github = "username"
    #social_email = "example@example.com"
    #social_google_plus = "profileid"

[params] # theme parameters
    author = "FgetDaPain" # author's name
    info = "Pythoner and Penetration Tester" # author's job title or info
    description = "FgetDaPain's personal website" # site description
    keywords = "blog,developer,personal" # site keywords
    
#theme = "coder"
## Social links
#[[params.social]]
#    name = "Github"
#    weight = 1
#    url = "https://github.com/johndoe/"
#[[params.social]]
#    name = "Twitter"
#    weight = 2
#    url = "https://twitter.com/johndoe/"
#[[params.social]]
#    name = "LinkedIn"
#    weight = 3
#    url = "https://www.linkedin.com/in/johndoe/"
#
## Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/posts/"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"


#theme = "whbcit8"
#[params]
#  aboutpage = "TK name-of-the-about-post" #This makes the "about" link in the header function.  It must be the exact filename of your about page without the file extension.  E.g. if your about page is called "mysiteabout.md" then enter in "mysiteabout"
#  author = "FgetDaPain" #Goes in the meta info of your webpage to help identify you as the author of the content
#  copyrightstatement = "Copyright by FgetDaPain." #Will appear in the footer of each page.
#  description = "describe in the html meta" #Goes in the meta info of your webpage to describe the content of your site
#  siteclass = "技术博客"  #If you set it, it will display a subtitle in a contrasting color (adjustable within the CSS) on the site's index page.
#  tagline = "安全、开发、生活" #Optional.  If you set it, it will display a tagline for the website underneath the titles.  By default it appears italicized.

